In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset['classification'].value_counts()

classification
yes    249
no     150
Name: count, dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             399 non-null    float64
 1   bp              399 non-null    float64
 2   sg              399 non-null    object
 3   al              399 non-null    int64
 4   su              399 non-null    int64
 5   rbc             399 non-null    object
 6   pc              399 non-null    object
 7   pcc             399 non-null    object
 8   ba              399 non-null    object
 9   bgr             399 non-null    float64
 10  bu              399 non-null    float64
 11  sc              399 non-null    float64
 12  sod             399 non-null    float64
 13  pot             399 non-null    float64
 14  hrmo            399 non-null    float64
 15  pcv             399 non-null    float64
 16  wc              399 non-null    float64
 17  rc              399 non-null    float64
 18  htn             399 non-null    object
 19  dm              399 non-null    object
 20  cad             399 non-null    object
 21  appet           399 non-null    object
 22  pe              399 non-null    object
 23  ane             399 non-null    object
 24  classification  399 non-null    object
dtypes: float64(11), int64(2), object(12)
memory usage: 78.1+ KB

In [6]:
dataset.isnull().sum()

age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hrmo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [7]:
dataset.shape

(399, 25)

In [8]:
def quanQual(dataset):
    quan=[]
    qual=[]
    for columnName in dataset.columns:
        #print(columnName)
        if(dataset[columnName].dtypes=='O'):
            #print("qual")
            qual.append(columnName)
        else:
            #print("quan")
            quan.append(columnName)
    return quan,qual

In [9]:
quanQual(dataset)

(['age',
  'bp',
  'al',
  'su',
  'bgr',
  'bu',
  'sc',
  'sod',
  'pot',
  'hrmo',
  'pcv',
  'wc',
  'rc'],
 ['sg',
  'rbc',
  'pc',
  'pcc',
  'ba',
  'htn',
  'dm',
  'cad',
  'appet',
  'pe',
  'ane',
  'classification'])

In [10]:
quan,qual=quanQual(dataset)

In [11]:
quan

['age',
 'bp',
 'al',
 'su',
 'bgr',
 'bu',
 'sc',
 'sod',
 'pot',
 'hrmo',
 'pcv',
 'wc',
 'rc']

In [12]:
qual

['sg',
 'rbc',
 'pc',
 'pcc',
 'ba',
 'htn',
 'dm',
 'cad',
 'appet',
 'pe',
 'ane',
 'classification']

In [13]:
import numpy as np
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(dataset[quan])
quan_data=imp.transform(dataset[quan])

In [14]:
quan_dataset=pd.DataFrame(quan_data)

In [15]:
quan_dataset

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,8408.191126,4.705597
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,34.000000,12300.000000,4.705597
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,34.000000,8408.191126,4.705597
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,38.868902,8408.191126,4.705597
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,36.000000,12400.000000,4.705597
...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,37.000000,9800.000000,4.400000
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,27.000000,8408.191126,4.705597
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,26.000000,9200.000000,3.400000
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,38.868902,8408.191126,4.705597
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,53.000000,8500.000000,4.900000

In [16]:
quan_dataset.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64

In [17]:
imp

SimpleImputer()

In [18]:
dataset_qual=pd.DataFrame(dataset[qual],columns=qual)

In [19]:
dataset_qual

,sg,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,classification
0,c,normal,abnormal,notpresent,notpresent,no,no,no,yes,yes,no,yes
1,c,normal,normal,notpresent,notpresent,no,no,no,yes,poor,no,yes
2,a,normal,normal,notpresent,notpresent,no,no,no,yes,poor,no,yes
3,d,normal,normal,notpresent,notpresent,no,no,no,yes,poor,yes,yes
4,c,normal,normal,notpresent,notpresent,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...
394,a,normal,normal,notpresent,notpresent,no,no,no,yes,poor,no,yes
395,c,normal,normal,notpresent,notpresent,yes,yes,no,yes,poor,yes,yes
396,c,normal,normal,notpresent,notpresent,yes,yes,no,poor,poor,no,yes
397,a,normal,normal,notpresent,notpresent,yes,yes,no,yes,poor,yes,yes
398,a,normal,normal,notpresent,notpresent,no,no,no,yes,poor,no,no

In [20]:
dataset_qual.shape

(399, 12)

In [21]:
dataset_qual.isnull().sum()

sg                0
rbc               0
pc                0
pcc               0
ba                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [22]:
for column in dataset_qual.columns:
    if dataset_qual[column].dtype == 'object':  # Check if the column contains categorical data
        dataset_qual[column].fillna('Unknown', inplace=True)

C:\Users\bammi\AppData\Local\Temp\ipykernel_18832\2441587757.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset_qual[column].fillna('Unknown', inplace=True)

In [23]:
dataset_qual.isnull().sum()

sg                0
rbc               0
pc                0
pcc               0
ba                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [24]:
final_dataset=pd.concat([quan_dataset,dataset_qual],axis=1)

In [25]:
final_dataset.reset_index(drop=True, inplace=True)

In [26]:
final_dataset

,0,1,2,3,4,5,6,7,8,9,...,pc,pcc,ba,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,abnormal,notpresent,notpresent,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,normal,notpresent,notpresent,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,normal,notpresent,notpresent,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,normal,notpresent,notpresent,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,normal,notpresent,notpresent,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,normal,notpresent,notpresent,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,normal,notpresent,notpresent,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,normal,notpresent,notpresent,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,normal,notpresent,notpresent,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,normal,notpresent,notpresent,no,no,no,yes,poor,no,no

In [27]:
final_dataset.shape

(399, 25)

In [28]:
final_dataset.isnull().sum()

0                 0
1                 0
2                 0
3                 0
4                 0
5                 0
6                 0
7                 0
8                 0
9                 0
10                0
11                0
12                0
sg                0
rbc               0
pc                0
pcc               0
ba                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64